name = "tetris"
description = "Tetris example for Raspberry Pico"
version = "0.1.0-dev"

authors = ["Elsa Ferrara"]
maintainers = ["Elsa Ferrara <ferrara@adacore.com>"]
maintainers-logins = ["elsaferrara"]

[[depends-on]]
gnat_arm_elf = "^12"
rp2040_hal = "^2.0"
pico_bsp = "^2.0"
chests = "~0.1.1"

 [[pins]]
rp2040_hal = {path="./rp2040_hal"}
pico_bsp = {path="./pico_bsp"}
